// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(LittleFrillDbContext))]
    [Migration("20260821144916_AdicionaCamposAdminProduto")]
    partial class AdicionaCamposAdminProduto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Encomenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoRastreio")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo_rastreio");

                    b.Property<DateTime>("Criada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada");

                    b.Property<DateTime?>("DataEmProducao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_em_producao");

                    b.Property<DateTime?>("DataEmbalada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_embalada");

                    b.Property<DateTime?>("DataEntregue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entregue");

                    b.Property<DateTime?>("DataEnviada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_enviada");

                    b.Property<decimal>("Envio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("envio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("MetodoEnvio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo_envio");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo_pagamento");

                    b.Property<string>("Nif")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("nif");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("referencia");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("integer")
                        .HasColumnName("utilizador_id");

                    b.HasKey("Id");

                    b.HasIndex("Referencia")
                        .IsUnique();

                    b.HasIndex("UtilizadorId");

                    b.ToTable("encomendas", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<List<int>>("CombinaCom")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("combina_com");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cor");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("custo");

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean")
                        .HasColumnName("destaque");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagem_url");

                    b.Property<string>("Medidas")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("medidas");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<bool>("Novo")
                        .HasColumnType("boolean")
                        .HasColumnName("novo");

                    b.Property<string>("Padrao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("padrao");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.Property<string>("Seccao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seccao");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<string>("Tecido")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("tecido");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CombinaCom = new List<int> { 5, 3 },
                            Cor = "Rosa",
                            Custo = 17.20m,
                            Destaque = false,
                            Medidas = "34 × 28 × 12 cm",
                            Nome = "Bolsa Alentejo",
                            Novo = true,
                            Padrao = "Xadrez",
                            Preco = 48m,
                            Seccao = "Acessorios",
                            Stock = 6,
                            Tecido = "Algodão xadrez, forro de sarja",
                            Tipo = "Bolsa"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CombinaCom = new List<int> { 4 },
                            Cor = "Verde",
                            Custo = 14.70m,
                            Destaque = false,
                            Medidas = "38 × 32 × 10 cm",
                            Nome = "Bolsa Tote de Linho",
                            Novo = false,
                            Padrao = "Liso",
                            Preco = 42m,
                            Seccao = "Acessorios",
                            Stock = 3,
                            Tecido = "Linho lavado, alças de fita",
                            Tipo = "Bolsa"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CombinaCom = new List<int> { 13, 5 },
                            Cor = "Lilas",
                            Custo = 8.40m,
                            Destaque = false,
                            Medidas = "24 × 15 × 9 cm",
                            Nome = "Necessaire Grande",
                            Novo = true,
                            Padrao = "Floral",
                            Preco = 26m,
                            Seccao = "Acessorios",
                            Stock = 12,
                            Tecido = "Algodão floral, interior impermeável",
                            Tipo = "Necessaire"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CombinaCom = new List<int> { 8 },
                            Cor = "Azul",
                            Custo = 6.30m,
                            Destaque = false,
                            Medidas = "18 × 11 × 7 cm",
                            Nome = "Necessaire Pequena",
                            Novo = false,
                            Padrao = "Xadrez",
                            Preco = 18m,
                            Seccao = "Acessorios",
                            Stock = 9,
                            Tecido = "Algodão xadrez, fecho de metal",
                            Tipo = "Necessaire"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CombinaCom = new List<int> { 1 },
                            Cor = "Rosa",
                            Custo = 3.10m,
                            Destaque = false,
                            Medidas = "11 × 9 cm",
                            Nome = "Porta-moedas Coração",
                            Novo = false,
                            Padrao = "Floral",
                            Preco = 12m,
                            Seccao = "Acessorios",
                            Stock = 20,
                            Tecido = "Retalhos de algodão, mola de metal",
                            Tipo = "Porta-moedas"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CombinaCom = new List<int> { 4, 5 },
                            Cor = "Amarelo",
                            Custo = 13.30m,
                            Destaque = false,
                            Medidas = "34 × 24 cm",
                            Nome = "Capa de Portátil 13\"",
                            Novo = false,
                            Padrao = "Xadrez",
                            Preco = 38m,
                            Seccao = "Acessorios",
                            Stock = 5,
                            Tecido = "Algodão acolchoado, velcro",
                            Tipo = "Capa"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CombinaCom = new List<int> { 3 },
                            Cor = "Azul",
                            Custo = 15.60m,
                            Destaque = false,
                            Medidas = "39 × 28 cm",
                            Nome = "Capa de Portátil 15\"",
                            Novo = false,
                            Padrao = "Liso",
                            Preco = 42m,
                            Seccao = "Acessorios",
                            Stock = 4,
                            Tecido = "Linho acolchoado, velcro",
                            Tipo = "Capa"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CombinaCom = new List<int> { 5 },
                            Cor = "Verde",
                            Custo = 7.70m,
                            Destaque = false,
                            Medidas = "19 × 14 cm",
                            Nome = "Capa de Kindle",
                            Novo = true,
                            Padrao = "Floral",
                            Preco = 22m,
                            Seccao = "Acessorios",
                            Stock = 7,
                            Tecido = "Algodão floral, elástico de fita",
                            Tipo = "Capa"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CombinaCom = new List<int> { 10 },
                            Cor = "Rosa",
                            Custo = 4.20m,
                            Destaque = false,
                            Medidas = "22 × 26 cm",
                            Nome = "Babete com folho",
                            Novo = false,
                            Padrao = "Xadrez",
                            Preco = 14m,
                            Seccao = "Bebe",
                            Stock = 15,
                            Tecido = "Algodão duplo, atrás em felpo",
                            Tipo = "Bebé"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CombinaCom = new List<int> { 9, 4 },
                            Cor = "Lilas",
                            Custo = 11.90m,
                            Destaque = false,
                            Medidas = "32 × 26 × 10 cm",
                            Nome = "Saco de fraldas",
                            Novo = false,
                            Padrao = "Floral",
                            Preco = 34m,
                            Seccao = "Bebe",
                            Stock = 6,
                            Tecido = "Algodão floral, bolsos interiores",
                            Tipo = "Bebé"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            CombinaCom = new List<int> { 12 },
                            Cor = "Verde",
                            Custo = 8.40m,
                            Destaque = false,
                            Medidas = "40 × 40 cm cada",
                            Nome = "Guardanapos (jogo de 4)",
                            Novo = false,
                            Padrao = "Xadrez",
                            Preco = 24m,
                            Seccao = "Mesa",
                            Stock = 10,
                            Tecido = "Linho, bainha à mão",
                            Tipo = "Mesa"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            CombinaCom = new List<int> { 11 },
                            Cor = "Amarelo",
                            Custo = 9.80m,
                            Destaque = false,
                            Medidas = "140 × 40 cm",
                            Nome = "Caminho de mesa",
                            Novo = true,
                            Padrao = "Liso",
                            Preco = 28m,
                            Seccao = "Mesa",
                            Stock = 5,
                            Tecido = "Linho lavado",
                            Tipo = "Mesa"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            CombinaCom = new List<int> { 14 },
                            Cor = "Azul",
                            Custo = 5.60m,
                            Destaque = false,
                            Medidas = "50 × 30 cm",
                            Nome = "Toalha de mão bordada",
                            Novo = false,
                            Padrao = "Floral",
                            Preco = 16m,
                            Seccao = "Banho",
                            Stock = 11,
                            Tecido = "Felpo com barra de algodão",
                            Tipo = "Banho"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            CombinaCom = new List<int> { 13 },
                            Cor = "Lilas",
                            Custo = 10.50m,
                            Destaque = false,
                            Medidas = "28 × 20 cm",
                            Nome = "Cesto de banho",
                            Novo = false,
                            Padrao = "Xadrez",
                            Preco = 30m,
                            Seccao = "Banho",
                            Stock = 3,
                            Tecido = "Algodão engomado, aro de vime",
                            Tipo = "Banho"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            CombinaCom = new List<int> { 16 },
                            Cor = "Rosa",
                            Custo = 11.20m,
                            Destaque = false,
                            Medidas = "50 × 70 cm",
                            Nome = "Fronha com folho",
                            Novo = false,
                            Padrao = "Floral",
                            Preco = 32m,
                            Seccao = "Cama",
                            Stock = 8,
                            Tecido = "Percal de algodão",
                            Tipo = "Cama"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            CombinaCom = new List<int> { 15 },
                            Cor = "Lilas",
                            Custo = 30.10m,
                            Destaque = false,
                            Medidas = "220 × 240 cm",
                            Nome = "Colcha de retalhos",
                            Novo = false,
                            Padrao = "Xadrez",
                            Preco = 86m,
                            Seccao = "Cama",
                            Stock = 2,
                            Tecido = "Retalhos de algodão, enchimento fino",
                            Tipo = "Cama"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            CombinaCom = new List<int> { 18 },
                            Cor = "Rosa",
                            Custo = 5.10m,
                            Destaque = false,
                            Medidas = "30 × 18 cm",
                            Nome = "Luva de forno",
                            Novo = false,
                            Padrao = "Listras",
                            Preco = 15m,
                            Seccao = "Cozinha",
                            Stock = 14,
                            Tecido = "Algodão com manta térmica",
                            Tipo = "Cozinha"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            CombinaCom = new List<int> { 17 },
                            Cor = "Amarelo",
                            Custo = 11.90m,
                            Destaque = false,
                            Medidas = "Tamanho único, fitas 1,2 m",
                            Nome = "Avental com folho",
                            Novo = true,
                            Padrao = "Floral",
                            Preco = 34m,
                            Seccao = "Cozinha",
                            Stock = 6,
                            Tecido = "Algodão floral, bolso frontal",
                            Tipo = "Cozinha"
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            CombinaCom = new List<int> { 20 },
                            Cor = "Azul",
                            Custo = 14.50m,
                            Destaque = false,
                            Medidas = "50 × 40 cm",
                            Nome = "Cama para gato",
                            Novo = false,
                            Padrao = "Xadrez",
                            Preco = 40m,
                            Seccao = "Animais",
                            Stock = 4,
                            Tecido = "Algodão xadrez, enchimento lavável",
                            Tipo = "Pets"
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            CombinaCom = new List<int> { 19 },
                            Cor = "Verde",
                            Custo = 3.15m,
                            Destaque = false,
                            Medidas = "Ajustável 26–40 cm",
                            Nome = "Bandana para cão",
                            Novo = false,
                            Padrao = "Listras",
                            Preco = 9m,
                            Seccao = "Animais",
                            Stock = 22,
                            Tecido = "Algodão, botão de pressão",
                            Tipo = "Pets"
                        });
                });

            modelBuilder.Entity("Core.Entities.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("codigo_postal");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Distrito")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("distrito");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("QuerCarta")
                        .HasColumnType("boolean")
                        .HasColumnName("quer_carta");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Cliente")
                        .HasColumnName("role");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sobrenome");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utilizadores", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Encomenda", b =>
                {
                    b.HasOne("Core.Entities.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Entities.Endereco", "Entrega", b1 =>
                        {
                            b1.Property<int>("EncomendaId")
                                .HasColumnType("integer");

                            b1.Property<string>("AndarPorta")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("entrega_andar_porta");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("entrega_codigo_postal");

                            b1.Property<string>("Distrito")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("entrega_distrito");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("entrega_email");

                            b1.Property<string>("Localidade")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("entrega_localidade");

                            b1.Property<string>("Morada")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("entrega_morada");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("entrega_nome");

                            b1.Property<string>("Notas")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("entrega_notas");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("entrega_pais");

                            b1.Property<string>("Telefone")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("entrega_telefone");

                            b1.HasKey("EncomendaId");

                            b1.ToTable("encomendas");

                            b1.WithOwner()
                                .HasForeignKey("EncomendaId");
                        });

                    b.OwnsMany("Core.Entities.EncomendaItem", "Itens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("NomeProduto")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nome_produto");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("preco_unitario");

                            b1.Property<int>("ProdutoId")
                                .HasColumnType("integer")
                                .HasColumnName("produto_id");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("integer")
                                .HasColumnName("quantidade");

                            b1.Property<int>("encomenda_id")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("encomenda_id");

                            b1.ToTable("encomenda_itens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("encomenda_id");
                        });

                    b.Navigation("Entrega")
                        .IsRequired();

                    b.Navigation("Itens");

                    b.Navigation("Utilizador");
                });
#pragma warning restore 612, 618
        }
    }
}
